#!/bin/bash
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/average_contract_value.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/Average_conversion_rate.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/Average_lazy_factor.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/customer_zone_total_revenue_product.py
/home/salesfokin/dataanalytics/bin/python3 ./leadscore.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/leadstage_sub_count.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/net_promoter_score.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/percentage_time_selling.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/pipeline.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/pipeline_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/productsales.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/productsales_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/product_customer_count.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/product_main_categ_leadcount.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/product_main_categ_leadcount_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/product_sub_main_count.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/sales_expense_ratio.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/userdata_leadsource.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/userdata_leadstage.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/userdata_leadstatus.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/user_avg_revenue.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/user_lead_activity.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/user_main_product_leadcount.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/user_per_product_revenue.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/win_rate.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zonedata_leadsource.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zonedata_leadsource_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zonedata_leadstage.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zonedata_leadstage_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zonedata_leadstatus.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zonedata_leadstatus_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_achieved.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_achieved_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_avg_revenue_per_user.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_avg_revenue_per_user_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lead_activity.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lead_activity_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lead_allocation.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lead_allocation_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lead_bdo.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lead_created.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lead_uploaded.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_lifetime.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_performance.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_quota_attainment.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_revenue_per_product_categ.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_revenue_per_product_categ_allyear_allmonth.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_source_stage.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_total_revenue_per_product_categ.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_total_revenue_per_user.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_uploaded_bdo.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_user_converted.py
/home/salesfokin/dataanalytics/bin/python3 ./da/dashboard/zone_user_converted_allyear_allmonth.py